import { Category, Product } from '@/components/buy-and-sell/types'

export const mockProducts: Product[] = [
  {
    id: 1,
    title: 'Casio FX-991EX Calculator',
    price: 800,
    category: 'stationery',
    description:
      'Used for 1 semester. Works perfectly, no scratches. Original box included.',
    image: '🔢',
    sellerName: 'Aman S.',
    whatsapp: '919876543210',
    date: '3 hours ago',
  },
  {
    id: 2,
    title: 'Data Structures by Cormen (CLRS)',
    price: 350,
    category: 'books',
    description:
      'Hardcover, 3rd edition. Some highlights in the first few chapters. Great condition.',
    image: '📘',
    sellerName: 'Priya M.',
    whatsapp: '919876543211',
    date: '6 hours ago',
  },
  {
    id: 3,
    title: 'Logitech Wireless Mouse',
    price: 500,
    category: 'tech',
    description: 'M331 silent mouse. Battery lasts 12 months. Used for 3 months.',
    image: '🖱️',
    sellerName: 'Rahul K.',
    whatsapp: '919876543212',
    date: '1 day ago',
  },
  {
    id: 4,
    title: 'Engineering Drawing Kit',
    price: 200,
    category: 'stationery',
    description:
      'Complete drawing set with compass, divider, rulers. Used for first year only.',
    image: '📐',
    sellerName: 'Dev P.',
    whatsapp: '919876543213',
    date: '1 day ago',
  },
  {
    id: 5,
    title: 'Operating Systems by Galvin',
    price: 250,
    category: 'books',
    description: '9th edition, paperback. Clean copy with no marks.',
    image: '📗',
    sellerName: 'Sneha R.',
    whatsapp: '919876543214',
    date: '2 days ago',
  },
  {
    id: 6,
    title: 'USB-C Hub 7-in-1',
    price: 1200,
    category: 'tech',
    description: 'Supports HDMI, USB 3.0, SD card. Used with MacBook for 4 months.',
    image: '🔌',
    sellerName: 'Kiran T.',
    whatsapp: '919876543215',
    date: '3 days ago',
  },
  {
    id: 7,
    title: 'Whiteboard Markers Set',
    price: 100,
    category: 'stationery',
    description: 'Pack of 10 assorted colors. Brand new, unopened.',
    image: '🖊️',
    sellerName: 'Meera J.',
    whatsapp: '919876543216',
    date: '3 days ago',
  },
  {
    id: 8,
    title: 'Raspberry Pi 4 (4GB)',
    price: 3500,
    category: 'tech',
    description:
      'Comes with case, power supply, and 32GB SD card. Used for one project.',
    image: '🍓',
    sellerName: 'Arjun V.',
    whatsapp: '919876543217',
    date: '4 days ago',
  },
]

export const categories: { label: string; value: Category }[] = [
  { label: 'All', value: 'all' },
  { label: 'Stationery', value: 'stationery' },
  { label: 'Books', value: 'books' },
  { label: 'Tech', value: 'tech' },
  { label: 'Other', value: 'other' },
]
