import { Note } from '@/components/notes/types'

export const subjects = [
  'All Subjects',
  'Data Structures',
  'Operating Systems',
  'DBMS',
  'Computer Networks',
  'Digital Logic',
  'Mathematics',
  'Physics',
  'Chemistry',
  'Engineering Drawing',
  'Software Engineering',
]

export const mockNotes: Note[] = [
  {
    id: 1,
    type: 'official',
    title: 'Unit 1 - Introduction to Data Structures',
    subject: 'Data Structures',
    description:
      'Covers arrays, linked lists, stacks, and queues with implementation details.',
    uploadedBy: 'Prof. Sharma',
    date: '1 day ago',
    upvotes: 0,
    downvotes: 0,
    userVote: null,
    fileUrl: '#',
  },
  {
    id: 2,
    type: 'official',
    title: 'Process Management - Complete Notes',
    subject: 'Operating Systems',
    description:
      'Process lifecycle, scheduling algorithms, inter-process communication.',
    uploadedBy: 'Prof. Gupta',
    date: '3 days ago',
    upvotes: 0,
    downvotes: 0,
    userVote: null,
    fileUrl: '#',
  },
  {
    id: 3,
    type: 'official',
    title: 'ER Model and Normalization',
    subject: 'DBMS',
    description:
      'Entity-Relationship diagrams, 1NF to BCNF normalization with examples.',
    uploadedBy: 'Prof. Verma',
    date: '1 week ago',
    upvotes: 0,
    downvotes: 0,
    userVote: null,
    fileUrl: '#',
  },
  {
    id: 4,
    type: 'community',
    title: 'Short notes - Trees & BST (with diagrams)',
    subject: 'Data Structures',
    description:
      'Handwritten notes with clear diagrams for binary trees, BST operations, AVL trees.',
    uploadedBy: 'Rahul K.',
    date: '2 days ago',
    upvotes: 24,
    downvotes: 2,
    userVote: null,
    fileUrl: '#',
  },
  {
    id: 5,
    type: 'community',
    title: 'OS Previous Year Solved Questions',
    subject: 'Operating Systems',
    description: 'Solved PYQs from 2020-2025 with step-by-step explanations.',
    uploadedBy: 'Priya M.',
    date: '4 days ago',
    upvotes: 45,
    downvotes: 1,
    userVote: null,
    fileUrl: '#',
  },
  {
    id: 6,
    type: 'community',
    title: 'SQL Cheat Sheet',
    subject: 'DBMS',
    description:
      'Quick reference for all SQL commands, joins, subqueries, and aggregate functions.',
    uploadedBy: 'Aman S.',
    date: '5 days ago',
    upvotes: 31,
    downvotes: 3,
    userVote: null,
    fileUrl: '#',
  },
  {
    id: 7,
    type: 'community',
    title: 'Computer Networks - One Shot Notes',
    subject: 'Computer Networks',
    description:
      'All 5 units covered in concise format. Great for last-minute revision.',
    uploadedBy: 'Dev P.',
    date: '1 week ago',
    upvotes: 52,
    downvotes: 5,
    userVote: null,
    fileUrl: '#',
  },
  {
    id: 8,
    type: 'community',
    title: 'Boolean Algebra Simplified',
    subject: 'Digital Logic',
    description:
      'K-maps, Boolean expressions, minimization techniques with solved examples.',
    uploadedBy: 'Sneha R.',
    date: '1 week ago',
    upvotes: 18,
    downvotes: 0,
    userVote: null,
    fileUrl: '#',
  },
]

export const reportReasons = [
  'Wrong subject',
  'Offensive content',
  'Obscene content',
  'Spam',
  'Copyright violation',
]
